### ISSUE TITLE
DP Singleton in Java

### ISSUE THREAD

**Issue by Thevapriyan07** [Thevapriyan07/Design-Patterns-Resources#3]
Need to make a readme file which should have the

Definition
Explanation in simple terms
Code related explanation.

**Comment by imshaaz21** [comment]
Hello, I'm eager to participate in Hacktoberfest and contribute to your project. Could you please assign me this issue?

**Comment by Thevapriyan07** [comment]
https://github.com/Thevapriyan07/Design-Patterns-Resources/pull/12/
